using System;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Text.Json;
using Microsoft.Win32;

namespace PC.SecurityAgent.Hardware
{
    public class HardwareProfileData
    {
        public string MotherboardManufacturer { get; set; } = "Unknown";
        public string MotherboardProduct { get; set; } = "Unknown";
        public string BiosVendor { get; set; } = "Unknown";
        public string BiosVersion { get; set; } = "Unknown";
        public string BootMode { get; set; } = "Unknown";
        public bool SecureBootEnabled { get; set; }
        public string PrimaryMac { get; set; } = "Unknown";
        public string PrimaryIp { get; set; } = "Unknown";
        public string HostName { get; set; } = "Unknown";
        public string UserName { get; set; } = "Unknown";
    }

    public static class HardwareProfile
    {
        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GetFirmwareType(ref uint firmwareType);

        private static HardwareProfileData? _cached;
        private static readonly object _lock = new();

        public static HardwareProfileData Current
        {
            get
            {
                if (_cached == null)
                {
                    lock (_lock)
                    {
                        _cached ??= LoadOrScan();
                    }
                }
                return _cached;
            }
        }

        private static HardwareProfileData LoadOrScan()
        {
            var profile = new HardwareProfileData
            {
                HostName = Environment.MachineName,
                UserName = Environment.UserName
            };

            // 1. Try reading pre-flight audit generated by DeployManager
            string auditFile = @"C:\Program Files\PCSecuritySystem\hardware_audit.json";
            if (File.Exists(auditFile))
            {
                try
                {
                    string json = File.ReadAllText(auditFile);
                    using var doc = JsonDocument.Parse(json);
                    var root = doc.RootElement;

                    if (root.TryGetProperty("Motherboard", out var mb))
                    {
                        profile.MotherboardManufacturer = mb.GetProperty("Manufacturer").GetString() ?? "Unknown";
                        profile.MotherboardProduct = mb.GetProperty("Product").GetString() ?? "Unknown";
                    }

                    if (root.TryGetProperty("Bios", out var bios))
                    {
                        profile.BiosVendor = bios.GetProperty("Vendor").GetString() ?? "Unknown";
                        profile.BiosVersion = bios.GetProperty("Version").GetString() ?? "Unknown";
                        profile.BootMode = bios.GetProperty("BootMode").GetString() ?? "Unknown";
                        profile.SecureBootEnabled = bios.GetProperty("SecureBootEnabled").GetBoolean();
                    }

                    if (root.TryGetProperty("Network", out var net))
                    {
                        profile.PrimaryMac = net.GetProperty("PrimaryMacAddress").GetString() ?? "Unknown";
                        profile.PrimaryIp = net.GetProperty("PrimaryIpAddress").GetString() ?? "Unknown";
                    }

                    return profile;
                }
                catch { }
            }

            // 2. Fallback live inspection
            try
            {
                using var baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64);
                using var biosKey = baseKey.OpenSubKey(@"HARDWARE\DESCRIPTION\System\BIOS");
                if (biosKey != null)
                {
                    profile.MotherboardManufacturer = biosKey.GetValue("BaseBoardManufacturer")?.ToString()?.Trim() ?? "Unknown";
                    profile.MotherboardProduct = biosKey.GetValue("BaseBoardProduct")?.ToString()?.Trim() ?? "Unknown";
                    profile.BiosVendor = biosKey.GetValue("BIOSVendor")?.ToString()?.Trim() ?? "Unknown";
                    profile.BiosVersion = biosKey.GetValue("BIOSVersion")?.ToString()?.Trim() ?? "Unknown";
                }

                uint firmwareType = 0;
                if (GetFirmwareType(ref firmwareType))
                {
                    profile.BootMode = firmwareType switch
                    {
                        2 => "Legacy BIOS",
                        3 => "UEFI Native",
                        _ => "Unknown"
                    };
                }

                using var secureBootKey = baseKey.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\SecureBoot\State");
                if (secureBootKey != null)
                {
                    object? val = secureBootKey.GetValue("UEFISecureBootEnabled");
                    if (val is int intVal) profile.SecureBootEnabled = (intVal == 1);
                }
            }
            catch { }

            // Live Network MAC & IP
            try
            {
                foreach (var nic in NetworkInterface.GetAllNetworkInterfaces())
                {
                    if (nic.OperationalStatus == OperationalStatus.Up &&
                        nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
                    {
                        var phys = nic.GetPhysicalAddress();
                        if (phys != null && phys.GetAddressBytes().Length > 0)
                        {
                            profile.PrimaryMac = string.Join(":", phys.GetAddressBytes().Select(b => b.ToString("X2")));
                        }

                        foreach (var u in nic.GetIPProperties().UnicastAddresses)
                        {
                            if (u.Address.AddressFamily == AddressFamily.InterNetwork)
                            {
                                profile.PrimaryIp = u.Address.ToString();
                                break;
                            }
                        }

                        if (profile.PrimaryMac != "Unknown" && profile.PrimaryIp != "Unknown") break;
                    }
                }
            }
            catch { }

            return profile;
        }
    }
}
