using System;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Text.Json;
using Microsoft.Win32;

namespace PC.SecurityAgent.Hardware
{
    public class HardwareProfileData
    {
        public string MotherboardManufacturer { get; set; } = "Unknown";
        public string MotherboardProduct { get; set; } = "Unknown";
        public string BiosVendor { get; set; } = "Unknown";
        public string BiosVersion { get; set; } = "Unknown";
        public string BootMode { get; set; } = "Unknown";
        public bool SecureBootEnabled { get; set; }
        public string PrimaryMac { get; set; } = "Unknown";
        public string PrimaryIp { get; set; } = "Unknown";
        public string HostName { get; set; } = "Unknown";
        public string UserName { get; set; } = "Unknown";

        // Extended Graphics, Network Driver, Storage, and Pre-boot properties
        public string GpuName { get; set; } = "Unknown GPU";
        public string GpuDriverPath { get; set; } = "Unknown";
        public bool UefiGopSupported { get; set; }
        public string PrimaryNetworkDriverPath { get; set; } = "Unknown";
        public bool PrebootUndiSupported { get; set; }
        public string StorageControllerName { get; set; } = "Unknown Controller";
        public string StorageDriverPath { get; set; } = "Unknown";
        public string PartitionStyle { get; set; } = "GPT";
        public string EspVolumeGuid { get; set; } = "Undetected";
        public bool PrebootReady { get; set; }
    }

    public static class HardwareProfile
    {
        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GetFirmwareType(ref uint firmwareType);

        private static HardwareProfileData? _cached;
        private static readonly object _lock = new();

        public static HardwareProfileData Current
        {
            get
            {
                if (_cached == null)
                {
                    lock (_lock)
                    {
                        _cached ??= LoadOrScan();
                    }
                }
                return _cached;
            }
        }

        private static HardwareProfileData LoadOrScan()
        {
            var profile = new HardwareProfileData
            {
                HostName = Environment.MachineName,
                UserName = Environment.UserName
            };

            // 1. Try reading pre-flight audit generated by DeployManager
            string auditFile = @"C:\Program Files\PCSecuritySystem\hardware_audit.json";
            if (File.Exists(auditFile))
            {
                try
                {
                    string json = File.ReadAllText(auditFile);
                    using var doc = JsonDocument.Parse(json);
                    var root = doc.RootElement;

                    if (root.TryGetProperty("Motherboard", out var mb))
                    {
                        profile.MotherboardManufacturer = mb.GetProperty("Manufacturer").GetString() ?? "Unknown";
                        profile.MotherboardProduct = mb.GetProperty("Product").GetString() ?? "Unknown";
                    }

                    if (root.TryGetProperty("Bios", out var bios))
                    {
                        profile.BiosVendor = bios.GetProperty("Vendor").GetString() ?? "Unknown";
                        profile.BiosVersion = bios.GetProperty("Version").GetString() ?? "Unknown";
                        profile.BootMode = bios.GetProperty("BootMode").GetString() ?? "Unknown";
                        profile.SecureBootEnabled = bios.GetProperty("SecureBootEnabled").GetBoolean();
                    }

                    if (root.TryGetProperty("Graphics", out var gfx))
                    {
                        profile.GpuName = gfx.GetProperty("GpuName").GetString() ?? "Unknown GPU";
                        profile.GpuDriverPath = gfx.GetProperty("DriverPath").GetString() ?? "Unknown";
                        if (gfx.TryGetProperty("UefiGopSupported", out var gopProp))
                        {
                            profile.UefiGopSupported = gopProp.GetBoolean();
                        }
                    }

                    if (root.TryGetProperty("Network", out var net))
                    {
                        profile.PrimaryMac = net.GetProperty("PrimaryMacAddress").GetString() ?? "Unknown";
                        profile.PrimaryIp = net.GetProperty("PrimaryIpAddress").GetString() ?? "Unknown";
                        if (net.TryGetProperty("PrimaryDriverPath", out var drvProp))
                        {
                            profile.PrimaryNetworkDriverPath = drvProp.GetString() ?? "Unknown";
                        }
                    }

                    if (root.TryGetProperty("Storage", out var storage))
                    {
                        profile.StorageControllerName = storage.GetProperty("PrimaryControllerName").GetString() ?? "Unknown Controller";
                        profile.StorageDriverPath = storage.GetProperty("DriverPath").GetString() ?? "Unknown";
                        profile.PartitionStyle = storage.GetProperty("PartitionStyle").GetString() ?? "GPT";
                    }

                    if (root.TryGetProperty("EfiPreboot", out var efi))
                    {
                        profile.EspVolumeGuid = efi.GetProperty("EspVolumeGuid").GetString() ?? "Undetected";
                        profile.PrebootReady = efi.GetProperty("PrebootReady").GetBoolean();
                    }

                    return profile;
                }
                catch { }
            }

            // 2. Fallback live inspection
            try
            {
                using var baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64);
                using var biosKey = baseKey.OpenSubKey(@"HARDWARE\DESCRIPTION\System\BIOS");
                if (biosKey != null)
                {
                    profile.MotherboardManufacturer = biosKey.GetValue("BaseBoardManufacturer")?.ToString()?.Trim() ?? "Unknown";
                    profile.MotherboardProduct = biosKey.GetValue("BaseBoardProduct")?.ToString()?.Trim() ?? "Unknown";
                    profile.BiosVendor = biosKey.GetValue("BIOSVendor")?.ToString()?.Trim() ?? "Unknown";
                    profile.BiosVersion = biosKey.GetValue("BIOSVersion")?.ToString()?.Trim() ?? "Unknown";
                }

                uint firmwareType = 0;
                if (GetFirmwareType(ref firmwareType))
                {
                    profile.BootMode = firmwareType switch
                    {
                        2 => "Legacy BIOS",
                        3 => "UEFI Native",
                        _ => "Unknown"
                    };
                }

                using var secureBootKey = baseKey.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\SecureBoot\State");
                if (secureBootKey != null)
                {
                    object? val = secureBootKey.GetValue("UEFISecureBootEnabled");
                    if (val is int intVal) profile.SecureBootEnabled = (intVal == 1);
                }

                // Live GPU inspect
                using var classKey = baseKey.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000");
                if (classKey != null)
                {
                    profile.GpuName = classKey.GetValue("DriverDesc")?.ToString()?.Trim() ?? "Unknown GPU";
                    profile.UefiGopSupported = profile.BootMode.Contains("UEFI");
                }
            }
            catch { }

            // Live Network MAC & IP
            try
            {
                foreach (var nic in NetworkInterface.GetAllNetworkInterfaces())
                {
                    if (nic.OperationalStatus == OperationalStatus.Up &&
                        nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
                    {
                        var phys = nic.GetPhysicalAddress();
                        if (phys != null && phys.GetAddressBytes().Length > 0)
                        {
                            profile.PrimaryMac = string.Join(":", phys.GetAddressBytes().Select(b => b.ToString("X2")));
                        }

                        foreach (var u in nic.GetIPProperties().UnicastAddresses)
                        {
                            if (u.Address.AddressFamily == AddressFamily.InterNetwork)
                            {
                                profile.PrimaryIp = u.Address.ToString();
                                break;
                            }
                        }

                        if (profile.PrimaryMac != "Unknown" && profile.PrimaryIp != "Unknown") break;
                    }
                }
            }
            catch { }

            return profile;
        }
    }
}
